In [21]:
import pandas as pd 
import numpy as np  


get_df =pd.read_csv("../data/Plant_1_Weather_Sensor_Data.csv")
weather_df = pd.read_csv("../data/Plant_1_Weather_Sensor_Data.csv")


get_df['DATE_TIME'] = pd.to_datetime(get_df["DATE_TIME"])
weather_df['DATE_TIME']=pd.to_datetime(weather_df["DATE_TIME"])

df = pd.merge(get_df, weather_df , on="DATE_TIME" ,how = 'inner')

print(df.shape)
df.head()

(3182, 11)

,DATE_TIME,PLANT_ID_x,SOURCE_KEY_x,AMBIENT_TEMPERATURE_x,MODULE_TEMPERATURE_x,IRRADIATION_x,PLANT_ID_y,SOURCE_KEY_y,AMBIENT_TEMPERATURE_y,MODULE_TEMPERATURE_y,IRRADIATION_y
0,2020-05-15 00:00:00,4135001,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0,4135001,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0
1,2020-05-15 00:15:00,4135001,HmiyD2TTLFNqkNe,25.084589,22.761668,0.0,4135001,HmiyD2TTLFNqkNe,25.084589,22.761668,0.0
2,2020-05-15 00:30:00,4135001,HmiyD2TTLFNqkNe,24.935753,22.592306,0.0,4135001,HmiyD2TTLFNqkNe,24.935753,22.592306,0.0
3,2020-05-15 00:45:00,4135001,HmiyD2TTLFNqkNe,24.846130,22.360852,0.0,4135001,HmiyD2TTLFNqkNe,24.846130,22.360852,0.0
4,2020-05-15 01:00:00,4135001,HmiyD2TTLFNqkNe,24.621525,22.165423,0.0,4135001,HmiyD2TTLFNqkNe,24.621525,22.165423,0.0

In [28]:
df.columns.tolist()

['DATE_TIME',
 'PLANT_ID_x',
 'SOURCE_KEY_x',
 'AMBIENT_TEMPERATURE_x',
 'MODULE_TEMPERATURE_x',
 'IRRADIATION_x',
 'PLANT_ID_y',
 'SOURCE_KEY_y',
 'AMBIENT_TEMPERATURE_y',
 'MODULE_TEMPERATURE_y',
 'IRRADIATION_y']

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3182 entries, 0 to 3181
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   DATE_TIME              3182 non-null   datetime64[ns]
 1   PLANT_ID_x             3182 non-null   int64
 2   SOURCE_KEY_x           3182 non-null   object
 3   AMBIENT_TEMPERATURE_x  3182 non-null   float64
 4   MODULE_TEMPERATURE_x   3182 non-null   float64
 5   IRRADIATION_x          3182 non-null   float64
 6   PLANT_ID_y             3182 non-null   int64
 7   SOURCE_KEY_y           3182 non-null   object
 8   AMBIENT_TEMPERATURE_y  3182 non-null   float64
 9   MODULE_TEMPERATURE_y   3182 non-null   float64
 10  IRRADIATION_y          3182 non-null   float64
dtypes: datetime64[ns](1), float64(6), int64(2), object(2)
memory usage: 273.6+ KB

In [33]:
columns_keep = [
    'DATE_TIME', 
    'PLANT_ID_x', 
    'AMBIENT_TEMPERATURE_x', 
    'MODULE_TEMPERATURE_x', 
    'IRRADIATION_x'
]

copy_col =df[columns_keep].copy()

copy_col.columns= [
    'date_time', 
    'plant_id', 
    'ambient_temp', 
    'module_temp', 
    'irradiation'
]

In [34]:
np.random.seed(42)
copy_col['dust_level']=np.random.uniform(0.1,0.9,len(copy_col))

In [35]:
def maintenace_logic(row):
    if row["dust_level"]>0.7 or row['module_temp']>60:
        return 1 
    else: 
        return 0 
copy_col['needs_maintenance']=copy_col.apply(maintenace_logic,axis=1)
print("done to add")

done to add

In [36]:
copy_col.head()

,date_time,plant_id,ambient_temp,module_temp,irradiation,dust_level,needs_maintenance
0,2020-05-15 00:00:00,4135001,25.184316,22.857507,0.0,0.399632,0
1,2020-05-15 00:15:00,4135001,25.084589,22.761668,0.0,0.860571,1
2,2020-05-15 00:30:00,4135001,24.935753,22.592306,0.0,0.685595,0
3,2020-05-15 00:45:00,4135001,24.846130,22.360852,0.0,0.578927,0
4,2020-05-15 01:00:00,4135001,24.621525,22.165423,0.0,0.224815,0

In [37]:

copy_col.to_csv('sudair_solar_ready_for_model.csv', index=False)

print("sudair_solar_ready_for_model.csv")
print(f"إجمالي عدد الصفوف: {copy_col.shape[0]}")
print(f"إجمالي عدد الأعمدة: {copy_col.shape[1]}")

sudair_solar_ready_for_model.csv
إجمالي عدد الصفوف: 3182
إجمالي عدد الأعمدة: 7